name: CI - Build and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: |
        cd server
        npm install

    - name: Run Linter
      run: |
        cd server
        npm run lint

    - name: Run SAST (Semgrep)
      uses: returntocorp/semgrep-action@v1
      with:
        config: "p/nodejs"

    - name: Run SCA (npm audit)
      run: |
        cd server
        npm audit --audit-level=high

    - name: Run Tests
      run: |
        cd server
        npm test

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=gabrielsarcan_Projeto-DevSecOps
          -Dsonar.organization=gabrielsarcan-1
          -Dsonar.sources=server,game/src
          -Dsonar.javascript.lcov.reportPaths=server/coverage/lcov.info
